/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package charger.client;

public class App {

    public static void main(String[] args) throws InterruptedException {
        new Client("49.254.35.106", 7888).connet();
    }
}
